### PR TITLE
 New files added

### PR DESCRIPTION
**Pull request by BuczynskiHubertTB**

### CODE REVIEW

**Comment by BuczynskiHubertTB** [comment]
validate

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Comment by BuczynskiHubertTB** [comment]
validation

**Review by Hubert2718 — DISMISSED** [review]

**Comment by Hubert2718** [comment]
validate

**Comment by Hubert2718** [comment]
validation

**Review by Hubert2718 — APPROVED** [review]

**Pull request merged**
